#!/usr/bin/env bash
#Configure your domain zone so that the subdomain www points to your load-balancer IP

func ()
{
	if [ -n "$1" ]; then
		if [ -n "$2" ]; then
			ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d "\n")
			record=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d "\n")
			echo "The subdomain $2 is a $record record and points to $ip"
		else
			ip=$(dig www."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d "\n")
			record=$(dig www."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d "\n")
			echo "The subdomain www is a $record record and points to $ip"
			ip=$(dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d "\n")
			record=$(dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d "\n")
			echo "The subdomain lb-01 is a $record record and points to $ip"
			ip=$(dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d "\n")
			record=$(dig web-01."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d "\n")
			echo "The subdomain web-01 is a $record record and points to $ip"
			ip=$(dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $5}' | tr -d "\n")
			record=$(dig web-02."$1" | grep -A1 'ANSWER SECTION:' | awk '{print $4}' | tr -d "\n")
			echo "The subdomain web-02 is a $record record and points to $ip"
		fi
	fi
}

func $1 $2
