#!/usr/bin/env bash
# Install nginx on server with default homepage string and redirection
sudo apt-get update

sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '\|root /var/www/html;|a\\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
