#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header

sudo apt-get update

sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i '\|root /var/www/html;|a\\n\tlocation /redirect_me/ {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

sudo sed -i '\|location \/ {|a\\t\tadd_header X-Served-By $hostname;' /etc/nginx/sites-available/default

sudo sed -i '\|root /var/www/html;|a\\n\terror_page 404 /404.html;\n' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo service nginx restart
