#!/usr/bin/env bash
# Configure HAproxy so that it send traffic to web-01 and web-02

sudo apt-get -y update
sudo apt-get -y install haproxy

sudo service haproxy start

echo 'frontend front_proxy
	bind *:80
	default_backend my_servers

backend my_servers
	balance roundrobin
	server web1 18.207.233.172:80
	server web2 34.201.165.206:80' | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy reload
