#!/usr/bin/env bash
# script that generates a MySQL dump and creates a compressed archive out of it

if [ $# -ne 0 ]; then
	file_name="$(date +"%d-%m-%Y").tar.gz"
	mysqldump -u root -p$1 --all-databases > backup.sql
	tar -cvzf $file_name backup.sql
fi
