#!/usr/bin/env bash
# this bash script

sudo bash -c 'echo "$$" > /var/run/myscript.pid'
exdel() {
	echo "I hate the kill command"
	sudo rm /var/run/myscript.pid
	exit 1
}
exdel1() {
	rm /var/run/myscript.pid
	exit 1
}
trap 'echo "Y u no love me?!"' SIGINT
trap exdel SIGTERM
trap exdel1 SIGQUIT
while true; do
	echo "To infinity and beyond"
	sleep 2
done
