#!/usr/bin/env bash
# this script groups visitors by IP and HTTP status code,
#+ and displays this data
#+ OCCURENCE_NUMBER IP HTTP_CODE
awk '{print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
